import { describe, expect, it } from "vitest"
import { createId, Id, type IdError } from "@/src/modules/shared/value-object/id"
import { createUuidIdGenerator } from "@/src/modules/shared/infra/id/uuid/uuid.id-generator"
import type { Result } from "@/src/modules/shared/result"
import type { IdGeneratorProvider } from "@/src/modules/shared/value-object/id/id-generator.provider"

const getErrorCodes = (idResult: Result<Id, IdError[]>): IdError["code"][] => {
  expect(idResult.fail).toBe(true)

  if (idResult.fail) {
    return idResult.error.map((error) => error.code)
  }

  return []
}

const VALID_V7_SAMPLES = [
  "0194f1a2-3b1a-7a2c-8e3d-1234567890ab",
  "0194f1a2-3b1a-7b3d-9e3d-abcdefabcdef",
  "0194f5a1-1234-7abc-8def-1234567890ab",
  "01950000-0000-7000-8000-000000000000",
]

const createStubProvider = (fixedValue: string): IdGeneratorProvider => {
  return {
    generate: () => fixedValue,
  }
}

const createSequentialProvider = (): IdGeneratorProvider => {
  let counter = 0
  return {
    generate: () => {
      const base = "0194f1a2-3b1a-7a2c-8e3d-"
      const suffix = String(counter++).padStart(12, "0")
      return `${base}${suffix}`
    },
  }
}

describe("Id.tryCreate", () => {
  it.each(VALID_V7_SAMPLES)("accept valid v7 id %s", (input) => {
    const idResult = Id.tryCreate(input)

    expect(idResult.success).toBe(true)

    if (idResult.success) {
      expect(idResult.value.value).toBe(input)
    }
  })

  it("accept v7 generated by provider", () => {
    const generated = Id.generate()
    const idResult = Id.tryCreate(generated.value)

    expect(idResult.success).toBe(true)
  })

  it.each([123, null, undefined, {}, [], true, 0])(
    "fail immediately with invalid type %s",
    (input) => {
      const idResult = Id.tryCreate(input)

      expect(getErrorCodes(idResult)).toEqual(["ID_INVALID_TYPE"])
    },
  )

  it.each(["", "   ", "\t", "\n"])("fail with required when input is %s", (input) => {
    const idResult = Id.tryCreate(input)

    expect(getErrorCodes(idResult)).toEqual(["ID_REQUIRED", "ID_INVALID_FORMAT"])
  })

  it.each([
    "not-a-uuid",
    "550e8400-e29b-41d4-a716-446655440000",
    "0194f1a2-3b1a-4a2c-8e3d-1234567890ab",
    "0194f1a2-3b1a-7a2c-0e3d-1234567890ab",
    "0194f1a2-3b1a-7a2c-8e3d-12345",
    "0194f1a23b1a7a2c8e3d1234567890ab",
    "0194f1a2-3b1a-7a2c-8e3d-1234567890abc",
    "0194f1a2-3b1a-7a2c-8e3d-zzzzzzzzzzzz",
  ])("reject invalid format %s", (input) => {
    const idResult = Id.tryCreate(input)

    expect(getErrorCodes(idResult)).toEqual(["ID_INVALID_FORMAT"])
  })

  it("accept uppercase v7", () => {
    const idResult = Id.tryCreate("0194F1A2-3B1A-7A2C-8E3D-1234567890AB")

    expect(idResult.success).toBe(true)
  })

  it("reject v4 uuid", () => {
    const v4 = "550e8400-e29b-41d4-a716-446655440000"
    const idResult = Id.tryCreate(v4)

    expect(getErrorCodes(idResult)).toEqual(["ID_INVALID_FORMAT"])
  })

  it("accumulate required and format for empty", () => {
    const idResult = Id.tryCreate("")

    expect(getErrorCodes(idResult)).toEqual(["ID_REQUIRED", "ID_INVALID_FORMAT"])
  })

  it("accumulate required and format for whitespace", () => {
    const idResult = Id.tryCreate("   ")

    expect(getErrorCodes(idResult)).toEqual(["ID_REQUIRED", "ID_INVALID_FORMAT"])
  })

  it("returns explicit success/fail flags without throwing", () => {
    const valid = Id.tryCreate(VALID_V7_SAMPLES[0])
    const invalid = Id.tryCreate(42)

    expect(valid.success).toBe(true)
    expect(valid.fail).toBe(false)
    expect(invalid.fail).toBe(true)
    expect(invalid.success).toBe(false)
  })
})

describe("Id.create", () => {
  it("create a valid id", () => {
    const id = Id.create(VALID_V7_SAMPLES[0])

    expect(id.value).toBe(VALID_V7_SAMPLES[0])
  })

  it.each(["", "   ", "not-a-uuid", "550e8400-e29b-41d4-a716-446655440000"])(
    "throw when creating invalid id %s",
    (input) => {
      expect(() => Id.create(input)).toThrow("Pré-condição do Id violada")
    },
  )

  it("throw for invalid type via tryCreate path", () => {
    // create expects string, so type check not needed, but invalid format still throws
    expect(() => Id.create("invalid")).toThrow()
  })

  it("never creates an invalid Id", () => {
    expect(() => Id.create("")).toThrow()
    expect(() => Id.create("0194f1a2-3b1a-4a2c-8e3d-1234567890ab")).toThrow()
  })
})

describe("Id.generate", () => {
  it("generate a valid v7 id", () => {
    const id = Id.generate()

    expect(id.value).toMatch(
      /^[0-9a-f]{8}-[0-9a-f]{4}-7[0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$/i,
    )

    const validation = Id.tryCreate(id.value)
    expect(validation.success).toBe(true)
  })

  it("generate unique ids", () => {
    const first = Id.generate()
    const second = Id.generate()

    expect(first.value).not.toBe(second.value)
  })

  it("generate sortable ids (lexicographically ordered by time)", async () => {
    const first = Id.generate()

    await new Promise((resolve) => setTimeout(resolve, 5))

    const second = Id.generate()

    expect(first.value < second.value).toBe(true)
  })

  it("generate via stub provider returns fixed value", () => {
    const stubId = createId(createStubProvider(VALID_V7_SAMPLES[0]))

    const generated = stubId.generate()

    expect(generated.value).toBe(VALID_V7_SAMPLES[0])
  })

  it("throw when provider generates invalid id", () => {
    const invalidProvider = createStubProvider("invalid-uuid")

    const brokenId = createId(invalidProvider)

    expect(() => brokenId.generate()).toThrow("Falha ao gerar Id válido")
  })

  it("generate is deterministic with sequential provider", () => {
    const sequential = createId(createSequentialProvider())

    const first = sequential.generate()
    const second = sequential.generate()

    expect(first.value).toBe("0194f1a2-3b1a-7a2c-8e3d-000000000000")
    expect(second.value).toBe("0194f1a2-3b1a-7a2c-8e3d-000000000001")
    expect(first.value < second.value).toBe(true)
  })
})

describe("Id.equals", () => {
  it("return true for equal ids", () => {
    const first = Id.create(VALID_V7_SAMPLES[0])
    const second = Id.create(VALID_V7_SAMPLES[0])

    expect(Id.equals(first, second)).toBe(true)
  })

  it("return false for different ids", () => {
    const first = Id.create(VALID_V7_SAMPLES[0])
    const second = Id.create(VALID_V7_SAMPLES[1])

    expect(Id.equals(first, second)).toBe(false)
  })
})

describe("Id.isValid", () => {
  it("return true for valid v7", () => {
    expect(Id.isValid(VALID_V7_SAMPLES[0])).toBe(true)
    expect(Id.isValid(VALID_V7_SAMPLES[0].toUpperCase())).toBe(true)
  })

  it("return false for invalid format", () => {
    expect(Id.isValid("not-a-uuid")).toBe(false)
    expect(Id.isValid("550e8400-e29b-41d4-a716-446655440000")).toBe(false)
  })

  it("return false for non-string", () => {
    expect(Id.isValid(123)).toBe(false)
    expect(Id.isValid(null)).toBe(false)
    expect(Id.isValid(undefined)).toBe(false)
  })
})

describe("Id immutability", () => {
  it("preserves original value", () => {
    const id = Id.create(VALID_V7_SAMPLES[0])

    expect(id.value).toBe(VALID_V7_SAMPLES[0])
  })
})

describe("IdProvider architecture", () => {
  it("compose Id with any provider implementation", () => {
    const stubId = createId(createStubProvider(VALID_V7_SAMPLES[1]))

    expect(stubId.generate().value).toBe(VALID_V7_SAMPLES[1])
    expect(stubId.isValid(VALID_V7_SAMPLES[1])).toBe(true)
  })

  it("create a generator using uuid that satisfies contract", () => {
    const provider = createUuidIdGenerator()
    const value = provider.generate()

    expect(value).toMatch(
      /^[0-9a-f]{8}-[0-9a-f]{4}-7[0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$/i,
    )
  })
})
